### ISSUE TITLE
Unable to compile LK library

### ISSUE THREAD

**Issue by kodandaravi724** [NREL/lk#44]
When trying to compile the LK library, I got the below error. I compiled in Windows machine 64 bit version and x86 architecture. 
**ind_package(wxWidgets REQUIRED xrc stc richtext ribbon propgrid aui gl html qa adv core xml net base)
        find_package(wxWidgets REQUIRED xrc stc richtext ribbon propgrid aui gl html qa adv core xml net base)
    find_package(wxWidgets REQUIRED qa webview aui richtext html propgrid adv net stc core base scintilla)**

However, I was able to download and compile wxWidgets successfully. After compiling wxWidgets do I need to add it to my PATH? 
Can anyone please help me with this issue?

**Comment by brtietz** [comment]
@kodandaravi724 Yes, wxWidgets needs to be added to your path. The up to date version of the instructions for all SAM repositories is here: https://github.com/NREL/SAM/wiki/Windows-Build-Instructions, with the path instructions under step 6. Are you doing an lk-only build or trying to build more of SAM?

**Comment by kodandaravi724** [comment]
Thanks for the response. What do I need to set the environment variable name for wxWidget? I couldn't find that information in the documentation.

**Comment by janinefreeman** [comment]
The environment variable name is WXMSW3 per Step 6.4 in the instructions above.
